// src/components/Navbar.tsx
import { navItems } from '@/data/siteData'
import { Bars3Icon, PhoneIcon, XMarkIcon } from '@heroicons/react/24/solid'
import { Link } from '@tanstack/react-router'
import { useCallback, useEffect, useState } from 'react'

export function Navbar(): React.ReactElement {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false)
  const [isScrolled, setIsScrolled] = useState(false)

  const toggleMobileMenu = useCallback(() => {
    setIsMobileMenuOpen((prev) => {
      const next = !prev
      document.body.style.overflow = next ? 'hidden' : ''
      return next
    })
  }, [])

  const closeMobileMenu = useCallback(() => {
    setIsMobileMenuOpen(false)
    document.body.style.overflow = ''
  }, [])

  useEffect(() => {
    function handleScroll(): void {
      setIsScrolled(window.scrollY > 50)
    }

    window.addEventListener('scroll', handleScroll)
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  return (
    <header>
      <nav
        className={`top-0 left-0 z-50 fixed bg-slate-100 w-full h-20 transition-all duration-300 ${
          isScrolled ? 'shadow-md' : 'shadow-none'
        }`}
      >
        <div className="flex justify-between items-center mx-auto px-6 h-full container">
          <Link to="/" className="flex items-center" onClick={closeMobileMenu}>
            <img
              src="/cbg-logo-transparent.png"
              alt="Cambridge Building Group Logo"
              className="w-auto h-14"
            />
          </Link>

          {/* Desktop Navigation */}
          <div className="hidden md:flex items-center gap-8">
            <ul className="flex justify-center items-center gap-x-6 font-bold text-navy uppercase">
              {Object.values(navItems).map((item) => (
                <li key={item.title} className="group relative">
                  <Link
                    to={item.link}
                    className="relative py-2 hover:text-slate-500 transition-colors duration-300"
                  >
                    {item.title}
                    <span className="bottom-0 left-0 absolute bg-navy w-0 group-hover:w-full h-0.5 transition-all duration-300" />
                  </Link>
                </li>
              ))}
            </ul>
            <Link
              to="/contact"
              className="flex items-center bg-navy hover:bg-transparent shadow px-4 py-2 border border-navy font-semibold text-slate-300 hover:text-navy transition duration-200"
            >
              <PhoneIcon className="mr-2 size-4" /> Get a Quote
            </Link>
          </div>

          {/* Mobile Menu Button */}
          <button
            type="button"
            className="md:hidden focus:outline-none text-navy"
            onClick={toggleMobileMenu}
            aria-label="Toggle navigation menu"
          >
            {isMobileMenuOpen ? <XMarkIcon className="size-8" /> : <Bars3Icon className="size-8" />}
          </button>
        </div>
      </nav>

      {/* Mobile Menu Overlay */}
      {isMobileMenuOpen && (
        <div
          role="button"
          tabIndex={0}
          className="z-40 fixed inset-0 bg-slate-900/50"
          onClick={closeMobileMenu}
          onKeyDown={(e) => {
            if (e.key === 'Escape' || e.key === 'Enter') closeMobileMenu()
          }}
        />
      )}

      {/* Mobile Menu Panel */}
      <div
        className={`top-20 right-0 bottom-0 z-50 fixed bg-slate-100 w-4/5 max-w-sm overflow-y-auto transition-transform duration-300 ease-in-out transform ${
          isMobileMenuOpen ? 'translate-x-0' : 'translate-x-full'
        }`}
      >
        <div className="px-6 py-8">
          <ul className="space-y-6">
            {Object.values(navItems).map((item) => (
              <li key={item.title}>
                <Link
                  to={item.link}
                  className="block font-bold text-navy hover:text-slate-500 text-xl transition duration-200"
                  onClick={closeMobileMenu}
                >
                  {item.title}
                </Link>
              </li>
            ))}
          </ul>
          <div className="mt-12 pt-6 border-slate-300 border-t">
            <Link
              to="/contact"
              className="block bg-navy hover:bg-slate-700 shadow px-4 py-3 w-full font-semibold text-slate-300 text-center transition duration-200"
              onClick={closeMobileMenu}
            >
              Get a Free Quote
            </Link>
            <div className="space-y-4 mt-8">
              <div className="flex items-center">
                <PhoneIcon className="mr-3 size-5 text-navy" />
                <a href="tel:6155557890" className="text-navy">
                  (615) 747-7007
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Spacer to offset fixed navbar */}
      <div className="h-20" />
    </header>
  )
}

// components/Navbar.vue
<script setup>
import { ref, onMounted, onUnmounted } from "vue";
import { Bars3Icon, XMarkIcon, PhoneIcon } from "@heroicons/vue/24/solid";
import { navItems } from "~/data/siteData";

// State for mobile menu
const isMobileMenuOpen = ref(false);
const isScrolled = ref(false);

// Function to toggle mobile menu
function toggleMobileMenu() {
  isMobileMenuOpen.value = !isMobileMenuOpen.value;

  // Prevent scrolling when menu is open
  if (isMobileMenuOpen.value) {
    document.body.style.overflow = "hidden";
  } else {
    document.body.style.overflow = "";
  }
}

// Function to close mobile menu
function closeMobileMenu() {
  isMobileMenuOpen.value = false;
  document.body.style.overflow = "";
}

// Function to check scroll position and update navbar style
function handleScroll() {
  isScrolled.value = window.scrollY > 50;
}

// Set up scroll event listener
onMounted(() => {
  window.addEventListener("scroll", handleScroll);
});

onUnmounted(() => {
  window.removeEventListener("scroll", handleScroll);
});
</script>

<template>
  <header>
    <!-- Main Navigation Bar -->
    <nav
      class="w-full h-20 fixed top-0 left-0 z-50 transition-all bg-slate-100 duration-300"
      :class="[
        isScrolled
          ? 'shadow-md'
          : 'shadow-none',
        isMobileMenuOpen ? 'bg-slate-100' : '',
      ]"
    >
      <div
        class="container mx-auto px-6 h-full flex justify-between items-center"
      >
        <!-- Logo -->
        <NuxtLink to="/" class="flex items-center" @click="closeMobileMenu">
          <NuxtImg
            src="/cbg-logo-transparent.png"
            alt="Cambridge Building Group Logo"
            class="h-14 w-auto"
            quality="100"
          />
        </NuxtLink>

        <!-- Desktop Menu -->
        <div class="hidden md:flex items-center gap-8">
          <ul
            class="flex gap-x-6 justify-center items-center text-navy font-bold uppercase"
          >
            <li
              v-for="item in Object.values(navItems)"
              :key="item.title"
              class="relative group"
            >
              <NuxtLink
                :to="item.link"
                class="py-2 transition-colors duration-300 hover:text-slate-500 relative"
              >
                {{ item.title }}
                <span
                  class="absolute bottom-0 left-0 w-0 h-0.5 bg-navy transition-all duration-300 group-hover:w-full"
                ></span>
              </NuxtLink>
            </li>
          </ul>

          <!-- CTA Button -->
          <NuxtLink
            to="/contact"
            class="bg-navy text-slate-300 font-semibold px-4 py-2 border border-navy shadow transition duration-200 hover:bg-transparent hover:text-navy flex items-center"
          >
            <PhoneIcon class="size-4 mr-2" />
            Get a Quote
          </NuxtLink>
        </div>

        <!-- Mobile Menu Toggle Button -->
        <button
          class="md:hidden text-navy focus:outline-none"
          @click="toggleMobileMenu"
          aria-label="Toggle navigation menu"
        >
          <Bars3Icon v-if="!isMobileMenuOpen" class="size-8" />
          <XMarkIcon v-else class="size-8" />
        </button>
      </div>
    </nav>

    <!-- Mobile Menu Overlay -->
    <div
      v-if="isMobileMenuOpen"
      class="fixed inset-0 bg-slate-900/50 z-40"
      @click="closeMobileMenu"
    ></div>

    <!-- Mobile Menu Panel -->
    <div
      class="fixed top-20 right-0 bottom-0 w-4/5 max-w-sm bg-slate-100 z-50 transform transition-transform duration-300 ease-in-out overflow-y-auto"
      :class="isMobileMenuOpen ? 'translate-x-0' : 'translate-x-full'"
    >
      <div class="px-6 py-8">
        <ul class="space-y-6">
          <li v-for="item in Object.values(navItems)" :key="item.title">
            <NuxtLink
              :to="item.link"
              class="block text-xl font-bold text-navy hover:text-slate-500 transition duration-200"
              @click="closeMobileMenu"
            >
              {{ item.title }}
            </NuxtLink>
          </li>
        </ul>

        <div class="mt-12 border-t border-slate-300 pt-6">
          <NuxtLink
            to="/contact"
            class="block w-full bg-navy text-slate-300 font-semibold px-4 py-3 text-center shadow transition duration-200 hover:bg-slate-700"
            @click="closeMobileMenu"
          >
            Get a Free Quote
          </NuxtLink>

          <div class="mt-8 space-y-4">
            <div class="flex items-center">
              <PhoneIcon class="size-5 text-navy mr-3" />
              <a href="tel:6155557890" class="text-navy">(615) 555-7890</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Spacer to prevent content from hiding behind fixed navbar -->
    <div class="h-20"></div>
  </header>
</template>

<style scoped>
body.no-scroll {
  overflow: hidden;
}
</style>
