// src/routes/privacy-policy.tsx
import { createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/privacy-policy')({
  component: PrivacyPolicyPage,
})

function PrivacyPolicyPage(): React.ReactElement {
  return (
    <div className="container mx-auto px-8 py-16">
      <h1 className="text-4xl font-bold text-navy mb-8">Privacy Policy</h1>
      <div className="prose max-w-none text-slate-700">
        <p>Last updated: December 31, 2025</p>
        <p>
          At Cambridge Building Group, we respect your privacy and are committed to protecting your
          personal data. This privacy policy will inform you as to how we look after your personal
          data when you visit our website and tell you about your privacy rights and how the law
          protects you.
        </p>
      </div>
    </div>
  )
}

// pages/privacy-policy.vue
<script setup>
useHead({
  title: "Privacy Policy | Cambridge Building Group",
  meta: [
    {
      name: "description",
      content: "Privacy Policy for Cambridge Building Group.",
    },
  ],
});
</script>

<template>
  <div class="container mx-auto px-8 py-16">
    <h1 class="text-4xl font-bold text-navy mb-8">Privacy Policy</h1>
    <div class="prose max-w-none text-slate-700">
      <p>Last updated: December 31, 2025</p>
      <p>
        At Cambridge Building Group, we respect your privacy and are committed to protecting your personal data.
        This privacy policy will inform you as to how we look after your personal data when you visit our website
        and tell you about your privacy rights and how the law protects you.
      </p>
      <!-- Add more content as needed -->
    </div>
  </div>
</template>
